"use client";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
async function api(init?:RequestInit){const {data}=await getSupabaseBrowserClient().auth.getSession();const r=await fetch("/api/admin/messenger",{...init,headers:{authorization:`Bearer ${data.session?.access_token??""}`,"content-type":"application/json"}});const j=await r.json();if(!r.ok)throw new Error(j.error);return j;}
async function apiOrg(init?:RequestInit){const {data}=await getSupabaseBrowserClient().auth.getSession();const r=await fetch("/api/admin/messenger/org",{...init,headers:{authorization:`Bearer ${data.session?.access_token??""}`,"content-type":"application/json"}});const j=await r.json();if(!r.ok)throw new Error(j.error);return j;}
export default function MessengerAdmin(){const [d,setD]=useState<any>();const [status,setStatus]=useState("");const [orgName, setOrgName]=useState("");const load=()=>api().then(setD).catch(e=>setStatus(e.message));useEffect(()=>{void load();},[]);async function save(user:any, form:HTMLFormElement){const fd=new FormData(form);await api({method:"POST",body:JSON.stringify({userId:user.id,organizationId:fd.get("org"),chatEnabled:fd.get("enabled")==="on",canDm:fd.get("dm")==="on",canOrgChat:fd.get("orgchat")==="on"})});setStatus(`${user.display_name||user.email} permissions saved.`);load();}
async function createOrg(e:React.FormEvent){e.preventDefault();try{await apiOrg({method:"POST",body:JSON.stringify({name:orgName})});setStatus(`Organization ${orgName} created.`);setOrgName("");load();}catch(e){setStatus(e instanceof Error?e.message:"Error creating organization");}}
if(!d)return <p className="p-6">Loading organization controls… {status}</p>;return <section className="grid gap-4"><header className="border border-white/10 bg-[#151517] p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-red-500">Admin only</p><h1 className="text-2xl font-black">Messenger Organizations</h1><p className="mt-1 text-sm text-white/55">Assign each NXTDox user to a dealership and award chat permissions.</p></header>{status&&<p className="bg-green-50 p-3 text-sm font-bold text-green-800">{status}</p>}
<div className="border border-black/10 bg-white p-5"><h2 className="mb-3 font-bold">Create Organization</h2><form onSubmit={createOrg} className="flex gap-2"><input type="text" value={orgName} onChange={e=>setOrgName(e.target.value)} required placeholder="Organization Name" className="h-11 flex-1 border px-3 text-sm" /><button className="h-11 rounded-[16px] bg-red-600 px-5 text-xs font-black uppercase tracking-wider text-white">Create</button></form></div>
<div className="grid gap-3">{d.users.map((u:any)=>{const m=d.memberships.find((x:any)=>x.user_id===u.id);return <details key={u.id} className="border border-black/10 bg-white" open={u.email==="xrkr80hd@gmail.com"}><summary className="cursor-pointer px-4 py-4 font-bold">{u.display_name||u.email}<span className="ml-2 text-xs font-normal text-black/45">{u.email}</span></summary><form onSubmit={e=>{e.preventDefault();save(u,e.currentTarget)}} className="grid gap-3 border-t p-4 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Organization<select name="org" defaultValue={m?.organization_id||""} required className="h-11 border px-3 text-sm"><option value="">Choose organization</option>{d.organizations.map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><div className="grid gap-2 text-sm"><label><input type="checkbox" name="enabled" defaultChecked={m?.chat_enabled}/> Enable NXTDox Messenger</label><label><input type="checkbox" name="dm" defaultChecked={m?.can_dm}/> Direct messages</label><label><input type="checkbox" name="orgchat" defaultChecked={m?.can_org_chat}/> Organization chat</label></div><button className="h-11 rounded-[16px] bg-red-600 px-5 text-xs font-black uppercase tracking-wider text-white sm:col-span-2">Save member permissions</button></form></details>})}</div></section>}
